<!-- src/routes/admin/(management)/announcementsDashboard/+page.svelte -->
<script lang="ts">
  import { enhance } from "$app/forms";
  import type { ActionData, PageData } from "./$types";
  import { renderAnnouncementMarkdown } from "$lib/markdown";

  let { data, form }: { data: PageData; form: ActionData } = $props();

  let isAdding = $state(false);
  let newText = $state("");
  let editingId = $state<string | null>(null);
  let editText = $state("");
  let savingId = $state<string | null>(null);

  function formatDate(date: string) {
    return new Date(date).toLocaleDateString("en-MY", {
      day: "numeric",
      month: "short",
      year: "numeric",
    });
  }

  function startEdit(id: string, currentText: string) {
    editingId = id;
    editText = currentText;
  }
</script>

<svelte:head>
  <title>Announcements - Admin AAR</title>
</svelte:head>

<div class="space-y-6">
  <p class="text-sm text-gray-500">
    Manually-curated items, shown first on the homepage "Pengumuman" feed, ahead
    of anything auto-generated by a sidebar content push. Max 10 — oldest drops
    off automatically when a new one is added. Supports <code class="text-xs"
      >**bold**</code
    >,
    <code class="text-xs">*italic*</code>, and
    <code class="text-xs">[text](url)</code> links.
  </p>

  {#if form?.message}
    <p class="text-sm text-red-600">{form.message}</p>
  {/if}

  <form
    method="POST"
    action="?/add"
    use:enhance={() => {
      isAdding = true;
      return async ({ update }) => {
        await update();
        newText = "";
        isAdding = false;
      };
    }}
    class="space-y-3 border-b border-gray-200 pb-6"
  >
    <label class="block">
      <span class="text-sm font-medium">Announcement text</span>
      <textarea
        name="text"
        bind:value={newText}
        rows="2"
        class="mt-1 w-full rounded border border-gray-300 p-2 font-mono text-sm"
        placeholder="**Modul baru** telah ditambah: Kerja Atap & Bumbung"
      ></textarea>
    </label>

    {#if newText.trim()}
      <div class="rounded bg-gray-50 border border-gray-200 p-3 text-sm">
        <span class="text-xs text-gray-400 block mb-1">Preview:</span>
        {@html renderAnnouncementMarkdown(newText)}
      </div>
    {/if}

    <button
      type="submit"
      disabled={isAdding || newText.trim().length === 0}
      class="rounded bg-gray-800 px-4 py-2 text-white disabled:opacity-50"
    >
      {isAdding ? "Menambah…" : "Tambah Pengumuman"}
    </button>
  </form>

  <ul class="space-y-3">
    {#each data.announcements as a (a.id)}
      <li class="rounded border border-gray-200 p-4">
        {#if editingId === a.id}
          <form
            method="POST"
            action="?/update"
            use:enhance={() => {
              savingId = a.id;
              return async ({ update }) => {
                await update();
                savingId = null;
                editingId = null;
              };
            }}
            class="space-y-2"
          >
            <input type="hidden" name="id" value={a.id} />
            <textarea
              name="text"
              bind:value={editText}
              rows="2"
              class="w-full rounded border border-gray-300 p-2 font-mono text-sm"
            ></textarea>
            {#if editText.trim()}
              <div
                class="rounded bg-gray-50 border border-gray-200 p-3 text-sm"
              >
                <span class="text-xs text-gray-400 block mb-1">Preview:</span>
                {@html renderAnnouncementMarkdown(editText)}
              </div>
            {/if}
            <div class="flex gap-2">
              <button
                type="submit"
                disabled={savingId === a.id || editText.trim().length === 0}
                class="rounded bg-gray-800 px-3 py-1.5 text-white text-sm disabled:opacity-50"
              >
                {savingId === a.id ? "Saving…" : "Save"}
              </button>
              <button
                type="button"
                onclick={() => (editingId = null)}
                class="rounded border border-gray-300 px-3 py-1.5 text-sm text-gray-600"
              >
                Cancel
              </button>
            </div>
          </form>
        {:else}
          <div class="flex items-start justify-between gap-4">
            <p class="text-sm text-gray-800">
              {@html renderAnnouncementMarkdown(a.text)}
            </p>
            <div class="flex gap-2 shrink-0">
              <button
                onclick={() => startEdit(a.id, a.text)}
                class="text-sm text-gray-600 hover:underline"
              >
                Edit
              </button>
              <form method="POST" action="?/remove" use:enhance>
                <input type="hidden" name="id" value={a.id} />
                <button
                  type="submit"
                  class="text-sm text-red-600 hover:underline"
                >
                  Delete
                </button>
              </form>
            </div>
          </div>
          <p class="text-xs text-gray-400 mt-1">{formatDate(a.created_at)}</p>
        {/if}
      </li>
    {:else}
      <li class="text-sm text-gray-500 text-center py-6">
        No announcements yet.
      </li>
    {/each}
  </ul>
</div>
