# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "LICENSE"
      - ".gitignore"

jobs:
  checks:
    runs-on: ubuntu-latest
    environment:
      name: productions
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci
    
      - name: Audit dependencies
        run: npm audit --audit-level=high

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run check
        env:
          PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${{vars.PUBLIC_SUPABASE_PUBLISHABLE_KEY}}
          PUBLIC_SUPABASE_URL: ${{vars.PUBLIC_SUPABASE_URL}}
          PUBLIC_TESTING_NGROK_URL: ${{vars.PUBLIC_TESTING_NGROK_URL}}
          PUBLIC_TURNSTILE_SITE_KEY: ${{vars.PUBLIC_TURNSTILE_SITE_KEY}}
          ADMIN_EMAILS: ADMIN_EMAILS
          CLIENT_SECRET_GOOGLE: CLIENT_SECRET_GOOGLE
          SUPABASE_SECRET_KEY: SUPABASE_SECRET_KEY
          TOYYIBPAY_BASE_URL: TOYYIBPAY_BASE_URL
          TOYYIBPAY_CATEGORY_CODE: TOYYIBPAY_CATEGORY_CODE
          TOYYIBPAY_SECRET_KEY: TOYYIBPAY_SECRET_KEY
          TURNSTILE_KEY: TURNSTILE_KEY
          PUBLIC_POSTHOG_HOST: PUBLIC_POSTHOG_HOST
          PUBLIC_POSTHOG_PROJECT_TOKEN: PUBLIC_POSTHOG_PROJECT_TOKEN
